services:
  backend:
    restart: unless-stopped
    build: ./backend
    expose:
      - 8081
  auth:
    restart: unless-stopped
    build: ./auth
    expose:
      - 8080
  frontend:
    restart: unless-stopped
    build: ./frontend
    expose:
      - 8080
  nginx:
    image: nginx
    restart: unless-stopped
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - backend
      - auth
    volumes:
      - ./nginx/templates:/etc/nginx/templates
