services:
  backend:
    restart: unless-stopped
    build: ./backend
    depends_on:
      - db
    expose:
      - 8081
    environment:
      DATABASE_URL: mysql://root:example@db:3306/database
  auth:
    restart: unless-stopped
    build: ./auth
    expose:
      - 8080
  frontend:
    restart: unless-stopped
    depends_on:
      - auth
      - backend
    build: ./frontend
    expose:
      - 8080
  nginx:
    image: nginx
    restart: unless-stopped
    ports: 
      - "80:80"
    depends_on:
      - frontend
      - backend
      - auth
    volumes:
      - ./nginx/templates:/etc/nginx/templates
  db:
    image: mariadb
    restart: always
    expose: 
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "database"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
