services:
  frontend:
    restart: unless-stopped
    build: ./frontend
    expose:
      - 8080 # since we configured frontend port to be 8080 in frontend/Dockerfile
  nginx:
    image: nginx
    restart: unless-stopped
    ports: 
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx/templates:/etc/nginx/templates
